In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.impute import SimpleImputer, KNNImputer

from copy import copy, deepcopy

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor

## Reading in all datasets

In [2]:
df_sh = pd.read_csv('data/ed_socio_health.csv')
df_wp = pd.read_csv('data/wage_poverty.csv')
df_un = pd.read_csv('data/unemployment_clean.csv')
df_fins = pd.read_csv('data/food_ins_18.csv')
df_ed = pd.read_csv('data/education_stats_dsi.csv')

In [3]:
df_sh.fips.astype(int)
df_wp.fips.astype(int)
df_un.fips.astype(int)
df_fins.fips.astype(int)
df_ed.fips.astype(int).head()

0    1001
1    1003
2    1005
3    1007
4    1009
Name: fips, dtype: int64

## Merge Dataframes
Merge each dataset into one main df

In [4]:
df_m = pd.merge(left = df_sh, right = df_wp, on = 'fips')
df_m = pd.merge(left = df_m, right = df_un, on = 'fips')
df_m = pd.merge(left = df_m, right = df_fins, on = 'fips')
df_m = pd.merge(left = df_m, right = df_ed, on = 'fips' )
df_m.shape

(3140, 86)

In [5]:
df_m.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3140 entries, 0 to 3139
Data columns (total 86 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   fips                                                           3140 non-null   int64
 1   state_x                                                        3140 non-null   object
 2   county                                                         3140 non-null   object
 3   lat                                                            3140 non-null   float64
 4   lon                                                            3140 non-null   float64
 5   total_population                                               3140 non-null   int64
 6   area_sqmi                                                      3140 non-null   float64
 7   population_density_per_sqmi                                    3140 non-null   float64
 8   percent_fair_or_poor_health                                    3140 non-null   float64
 9   average_number_of_mentally_unhealthy_days                      3140 non-null   float64
 10  percent_low_birthweight                                        3034 non-null   float64
 11  percent_smokers                                                3140 non-null   float64
 12  percent_adults_with_obesity                                    3140 non-null   float64
 13  food_environment_index                                         3121 non-null   float64
 14  percent_physically_inactive                                    3140 non-null   float64
 15  percent_with_access_to_exercise_opportunities                  3134 non-null   float64
 16  teen_birth_rate                                                2986 non-null   float64
 17  percent_uninsured                                              3140 non-null   float64
 18  primary_care_physicians_rate                                   2993 non-null   float64
 19  mental_health_provider_rate                                    2910 non-null   float64
 20  high_school_graduation_rate                                    3045 non-null   float64
 21  percent_some_college                                           3140 non-null   float64
 22  labor_force                                                    3140 non-null   float64
 23  percent_unemployed_CHR                                         3140 non-null   float64
 24  percent_children_in_poverty                                    3140 non-null   float64
 25  num_households_CHR                                             3139 non-null   float64
 26  percent_single_parent_households_CHR                           3139 non-null   float64
 27  violent_crime_rate                                             2950 non-null   float64
 28  percent_severe_housing_problems                                3140 non-null   float64
 29  severe_housing_cost_burden                                     3140 non-null   float64
 30  life_expectancy                                                3068 non-null   float64
 31  age_adjusted_death_rate                                        3081 non-null   float64
 32  child_mortality_rate                                           1910 non-null   float64
 33  infant_mortality_rate                                          1257 non-null   float64
 34  percent_adults_with_diabetes                                   3140 non-null   float64
 35  num_food_insecure                                              3140 non-null   int64
 36  percent_food_insecure                                          3140 non-null   float64
 37  num_limited_access_to_healthy_foods                            3121 non-null   float64
 38  percent_limited_access_to_healthy_foods                        3121 non-null   float64
 39  median_household_income                                        3140 non-null   float64
 40  percent_enrolled_in_free_or_reduced_lunch                      3019 non-null   float64
 41  segregation_index                                              2068 non-null   float64
 42  segregation_index_2                                            2790 non-null   float64
 43  homicide_rate                                                  1283 non-null   float64
 44  suicide_rate_age_adjusted                                      2378 non-null   float64
 45  juvenile_arrest_rate                                           2138 non-null   float64
 46  percent_homeowners                                             3140 non-null   float64
 47  percent_severe_housing_cost_burden                             3137 non-null   float64
 48  percent_less_than_18_years_of_age                              3140 non-null   float64
 49  percent_65_and_over                                            3140 non-null   float64
 50  percent_black                                                  3140 non-null   float64
 51  percent_american_indian_alaska_native                          3140 non-null   float64
 52  percent_asian                                                  3140 non-null   float64
 53  percent_native_hawaiian_other_pacific_islander                 3140 non-null   float64
 54  percent_hispanic                                               3140 non-null   float64
 55  percent_non_hispanic_white                                     3140 non-null   float64
 56  percent_not_proficient_in_english                              3140 non-null   float64
 57  percent_female                                                 3140 non-null   float64
 58  percent_rural                                                  3133 non-null   float64
 59  num_below_poverty                                              3140 non-null   int64
 60  per_capita_income                                              3140 non-null   float64
 61  percent_below_poverty                                          3140 non-null   float64
 62  percent_unemployed_CDC                                         3140 non-null   float64
 63  percent_no_highschool_diploma                                  3140 non-null   float64
 64  percent_age_65_and_older                                       3140 non-null   float64
 65  percent_age_17_and_younger                                     3140 non-null   float64
 66  percent_disabled                                               3140 non-null   float64
 67  percent_minorities                                             3140 non-null   float64
 68  percent_limited_english_abilities                              3140 non-null   float64
 69  percentile_rank_social_vulnerability                           3140 non-null   float64
 70  pct_overall_pov_19                                             3140 non-null   float64
 71  med_inc_19                                                     3140 non-null   object
 72  unemployment_rate_2019                                         3140 non-null   float64
 73  med_household_inc_19                                           3140 non-null   object
 74  med_hh_income_percent_of_state_total_2019                      3140 non-null   float64
 75  fi_rate_18                                                     3140 non-null   object
 76  ch_fi_rate_18                                                  3140 non-null   object
 77  cpm_18                                                         3140 non-null   object
 78  state_y                                                        3140 non-null   object
 79  area_name                                                      3140 non-null   object
 80  less_than_high_school_diploma                                  3140 non-null   object
 81  bachelor_degree_or_higher                                      3140 non-null   object
 82  percent_of_adults_with_less_than_high_school_diploma           3140 non-null   float64
 83  percent_of_adults_with_high_school_diploma_only                3140 non-null   float64
 84  percent_of_adults_completing_some_college_or_associate_degree  3140 non-null   float64
 85  percent_of_adults_with_bachelor_degree_or_higher               3140 non-null   float64
dtypes: float64(71), int64(4), object(11)
memory usage: 2.1+ MB

In [6]:
df_m.isnull().sum().sum()

9405

In [7]:
#crete csv
df_m.to_csv('data/df_full.csv', index = False)

## Check for Nulls

In [8]:
nulls = pd.DataFrame(df_m.isnull().sum())

In [9]:
nulls = nulls.reset_index()

In [10]:
#nulls.to_csv('./data/nulls.csv', index = False)

## Cleaning

#### Renaming state_x as full_st_name

In [11]:
df_m = df_m.rename(columns = {"state_x": "state_name",
                               "state_y": "state_abr"})

In [12]:
df_m.head()

,fips,state_name,county,lat,lon,total_population,area_sqmi,population_density_per_sqmi,percent_fair_or_poor_health,average_number_of_mentally_unhealthy_days,...,ch_fi_rate_18,cpm_18,state_abr,area_name,less_than_high_school_diploma,bachelor_degree_or_higher,percent_of_adults_with_less_than_high_school_diploma,percent_of_adults_with_high_school_diploma_only,percent_of_adults_completing_some_college_or_associate_degree,percent_of_adults_with_bachelor_degree_or_higher
0,1001,Alabama,Autauga,32.534928,-86.642748,55049,594.446120,92.605533,20.882987,4.654031,...,21.4%,US$3.33,AL,Autauga County,"4,291","9,929",11.5,33.6,28.4,26.6
1,1003,Alabama,Baldwin,30.727489,-87.722575,199510,1589.807425,125.493187,17.509134,4.304056,...,16.9%,US$3.58,AL,Baldwin County,"13,893","48,148",9.2,27.7,31.3,31.9
2,1005,Alabama,Barbour,31.869589,-85.393213,26614,884.875776,30.076538,29.591802,5.185594,...,32%,US$3.12,AL,Barbour County,"4,812","2,080",26.8,35.6,26.0,11.6
3,1007,Alabama,Bibb,32.998634,-87.126480,22572,622.582355,36.255444,19.439724,4.551699,...,20.9%,US$2.94,AL,Bibb County,"3,386","1,678",20.9,44.9,23.8,10.4
4,1009,Alabama,Blount,33.980878,-86.567383,57704,644.806508,89.490412,21.745293,4.891455,...,19.1%,US$3.14,AL,Blount County,"7,763","5,210",19.5,33.4,34.0,13.1

## Dropping unnecessary columns

Dropping columns that are unlikely to have explanatory power over and above other variables and that are duplicate information from 2016 data (eg. 2019 unemployment data).

Dropping num and percent food insecure in 2016 dataset as the 2018 data has both children and total.

In [13]:
df_m.shape

(3140, 86)

In [14]:
df_m.head()

,fips,state_name,county,lat,lon,total_population,area_sqmi,population_density_per_sqmi,percent_fair_or_poor_health,average_number_of_mentally_unhealthy_days,...,ch_fi_rate_18,cpm_18,state_abr,area_name,less_than_high_school_diploma,bachelor_degree_or_higher,percent_of_adults_with_less_than_high_school_diploma,percent_of_adults_with_high_school_diploma_only,percent_of_adults_completing_some_college_or_associate_degree,percent_of_adults_with_bachelor_degree_or_higher
0,1001,Alabama,Autauga,32.534928,-86.642748,55049,594.446120,92.605533,20.882987,4.654031,...,21.4%,US$3.33,AL,Autauga County,"4,291","9,929",11.5,33.6,28.4,26.6
1,1003,Alabama,Baldwin,30.727489,-87.722575,199510,1589.807425,125.493187,17.509134,4.304056,...,16.9%,US$3.58,AL,Baldwin County,"13,893","48,148",9.2,27.7,31.3,31.9
2,1005,Alabama,Barbour,31.869589,-85.393213,26614,884.875776,30.076538,29.591802,5.185594,...,32%,US$3.12,AL,Barbour County,"4,812","2,080",26.8,35.6,26.0,11.6
3,1007,Alabama,Bibb,32.998634,-87.126480,22572,622.582355,36.255444,19.439724,4.551699,...,20.9%,US$2.94,AL,Bibb County,"3,386","1,678",20.9,44.9,23.8,10.4
4,1009,Alabama,Blount,33.980878,-86.567383,57704,644.806508,89.490412,21.745293,4.891455,...,19.1%,US$3.14,AL,Blount County,"7,763","5,210",19.5,33.4,34.0,13.1

In [15]:
drop_list = ['teen_birth_rate', 'age_adjusted_death_rate', 'child_mortality_rate', 
             'infant_mortality_rate', 'num_limited_access_to_healthy_foods', 
             'segregation_index', 'segregation_index_2', 'homicide_rate', 
             'suicide_rate_age_adjusted', 'juvenile_arrest_rate', 'area_name', 
             'num_below_poverty', 'percent_some_college', 'labor_force', 
             'percent_unemployed_CHR', 'med_inc_19', 'unemployment_rate_2019', 
             'med_household_inc_19', 'med_hh_income_percent_of_state_total_2019', 
             'num_food_insecure', 'percent_food_insecure', 'less_than_high_school_diploma', 
             'bachelor_degree_or_higher', 'percent_less_than_18_years_of_age', 'percent_65_and_over', 
            'mental_health_provider_rate']

df_m = df_m.drop(columns = drop_list)
df_m.shape

(3140, 60)

In [16]:
df_m.head()

,fips,state_name,county,lat,lon,total_population,area_sqmi,population_density_per_sqmi,percent_fair_or_poor_health,average_number_of_mentally_unhealthy_days,...,percentile_rank_social_vulnerability,pct_overall_pov_19,fi_rate_18,ch_fi_rate_18,cpm_18,state_abr,percent_of_adults_with_less_than_high_school_diploma,percent_of_adults_with_high_school_diploma_only,percent_of_adults_completing_some_college_or_associate_degree,percent_of_adults_with_bachelor_degree_or_higher
0,1001,Alabama,Autauga,32.534928,-86.642748,55049,594.446120,92.605533,20.882987,4.654031,...,0.3773,12.1,15.6%,21.4%,US$3.33,AL,11.5,33.6,28.4,26.6
1,1003,Alabama,Baldwin,30.727489,-87.722575,199510,1589.807425,125.493187,17.509134,4.304056,...,0.2757,10.1,12.9%,16.9%,US$3.58,AL,9.2,27.7,31.3,31.9
2,1005,Alabama,Barbour,31.869589,-85.393213,26614,884.875776,30.076538,29.591802,5.185594,...,0.9847,27.1,21.9%,32%,US$3.12,AL,26.8,35.6,26.0,11.6
3,1007,Alabama,Bibb,32.998634,-87.126480,22572,622.582355,36.255444,19.439724,4.551699,...,0.5737,20.3,15.1%,20.9%,US$2.94,AL,20.9,44.9,23.8,10.4
4,1009,Alabama,Blount,33.980878,-86.567383,57704,644.806508,89.490412,21.745293,4.891455,...,0.4986,16.3,13.6%,19.1%,US$3.14,AL,19.5,33.4,34.0,13.1

## Drop % and convert to float

In [17]:
df_m['fi_rate_18'] = df_m['fi_rate_18'].str.replace('%', '').astype(float)
df_m['ch_fi_rate_18'] = df_m['ch_fi_rate_18'].str.replace('%', '').astype(float)
df_m['cpm_18'] = df_m['cpm_18'].str.strip('US$').astype(float)
df_m.head()

,fips,state_name,county,lat,lon,total_population,area_sqmi,population_density_per_sqmi,percent_fair_or_poor_health,average_number_of_mentally_unhealthy_days,...,percentile_rank_social_vulnerability,pct_overall_pov_19,fi_rate_18,ch_fi_rate_18,cpm_18,state_abr,percent_of_adults_with_less_than_high_school_diploma,percent_of_adults_with_high_school_diploma_only,percent_of_adults_completing_some_college_or_associate_degree,percent_of_adults_with_bachelor_degree_or_higher
0,1001,Alabama,Autauga,32.534928,-86.642748,55049,594.446120,92.605533,20.882987,4.654031,...,0.3773,12.1,15.6,21.4,3.33,AL,11.5,33.6,28.4,26.6
1,1003,Alabama,Baldwin,30.727489,-87.722575,199510,1589.807425,125.493187,17.509134,4.304056,...,0.2757,10.1,12.9,16.9,3.58,AL,9.2,27.7,31.3,31.9
2,1005,Alabama,Barbour,31.869589,-85.393213,26614,884.875776,30.076538,29.591802,5.185594,...,0.9847,27.1,21.9,32.0,3.12,AL,26.8,35.6,26.0,11.6
3,1007,Alabama,Bibb,32.998634,-87.126480,22572,622.582355,36.255444,19.439724,4.551699,...,0.5737,20.3,15.1,20.9,2.94,AL,20.9,44.9,23.8,10.4
4,1009,Alabama,Blount,33.980878,-86.567383,57704,644.806508,89.490412,21.745293,4.891455,...,0.4986,16.3,13.6,19.1,3.14,AL,19.5,33.4,34.0,13.1

In [18]:
# Check types
types = pd.DataFrame(df_m.dtypes)
types

                                                          0
fips                                                  int64
state_name                                           object
county                                               object
lat                                                 float64
lon                                                 float64
total_population                                      int64
area_sqmi                                           float64
population_density_per_sqmi                         float64
percent_fair_or_poor_health                         float64
average_number_of_mentally_unhealthy_days           float64
percent_low_birthweight                             float64
percent_smokers                                     float64
percent_adults_with_obesity                         float64
food_environment_index                              float64
percent_physically_inactive                         float64
percent_with_access_to_exercise_opportunities       float64
percent_uninsured                                   float64
primary_care_physicians_rate                        float64
high_school_graduation_rate                         float64
percent_children_in_poverty                         float64
num_households_CHR                                  float64
percent_single_parent_households_CHR                float64
violent_crime_rate                                  float64
percent_severe_housing_problems                     float64
severe_housing_cost_burden                          float64
life_expectancy                                     float64
percent_adults_with_diabetes                        float64
percent_limited_access_to_healthy_foods             float64
median_household_income                             float64
percent_enrolled_in_free_or_reduced_lunch           float64
percent_homeowners                                  float64
percent_severe_housing_cost_burden                  float64
percent_black                                       float64
percent_american_indian_alaska_native               float64
percent_asian                                       float64
percent_native_hawaiian_other_pacific_islander      float64
percent_hispanic                                    float64
percent_non_hispanic_white                          float64
percent_not_proficient_in_english                   float64
percent_female                                      float64
percent_rural                                       float64
per_capita_income                                   float64
percent_below_poverty                               float64
percent_unemployed_CDC                              float64
percent_no_highschool_diploma                       float64
percent_age_65_and_older                            float64
percent_age_17_and_younger                          float64
percent_disabled                                    float64
percent_minorities                                  float64
percent_limited_english_abilities                   float64
percentile_rank_social_vulnerability                float64
pct_overall_pov_19                                  float64
fi_rate_18                                          float64
ch_fi_rate_18                                       float64
cpm_18                                              float64
state_abr                                            object
percent_of_adults_with_less_than_high_school_di...  float64
percent_of_adults_with_high_school_diploma_only     float64
percent_of_adults_completing_some_college_or_as...  float64
percent_of_adults_with_bachelor_degree_or_higher    float64

## Impute Missing Data

In [19]:
df_m.isnull().sum()

fips                                                               0
state_name                                                         0
county                                                             0
lat                                                                0
lon                                                                0
total_population                                                   0
area_sqmi                                                          0
population_density_per_sqmi                                        0
percent_fair_or_poor_health                                        0
average_number_of_mentally_unhealthy_days                          0
percent_low_birthweight                                          106
percent_smokers                                                    0
percent_adults_with_obesity                                        0
food_environment_index                                            19
percent_physically_inactive                                        0
percent_with_access_to_exercise_opportunities                      6
percent_uninsured                                                  0
primary_care_physicians_rate                                     147
high_school_graduation_rate                                       95
percent_children_in_poverty                                        0
num_households_CHR                                                 1
percent_single_parent_households_CHR                               1
violent_crime_rate                                               190
percent_severe_housing_problems                                    0
severe_housing_cost_burden                                         0
life_expectancy                                                   72
percent_adults_with_diabetes                                       0
percent_limited_access_to_healthy_foods                           19
median_household_income                                            0
percent_enrolled_in_free_or_reduced_lunch                        121
percent_homeowners                                                 0
percent_severe_housing_cost_burden                                 3
percent_black                                                      0
percent_american_indian_alaska_native                              0
percent_asian                                                      0
percent_native_hawaiian_other_pacific_islander                     0
percent_hispanic                                                   0
percent_non_hispanic_white                                         0
percent_not_proficient_in_english                                  0
percent_female                                                     0
percent_rural                                                      7
per_capita_income                                                  0
percent_below_poverty                                              0
percent_unemployed_CDC                                             0
percent_no_highschool_diploma                                      0
percent_age_65_and_older                                           0
percent_age_17_and_younger                                         0
percent_disabled                                                   0
percent_minorities                                                 0
percent_limited_english_abilities                                  0
percentile_rank_social_vulnerability                               0
pct_overall_pov_19                                                 0
fi_rate_18                                                         0
ch_fi_rate_18                                                      0
cpm_18                                                             0
state_abr                                                          0
percent_of_adults_with_less_than_high_school_diploma               0
percent_of_adults_with_high_school_diploma_only                    0
percent_of_adults_completing_some_college_or_associate_degree      0
percent_of_adults_with_bachelor_degree_or_higher                   0
dtype: int64

In [20]:
# Total number of missing values
df_m.isnull().sum().sum()

787

In [21]:
null_columns = [col for col in df_m if df_m[col].isna().any()]

df_m_mean = deepcopy(df_m)
df_m_median = deepcopy(df_m)
df_m_mode = deepcopy(df_m)
df_m_knn = pd.get_dummies(deepcopy(df_m))
df_m_lr = pd.get_dummies(deepcopy(df_m))
df_m_rf = pd.get_dummies(deepcopy(df_m))

In [22]:
# Imputer with mean, median, mode
for col in null_columns:
    df_m_mean[col] = df_m[col].fillna(df_m[col].dropna().mean())
    df_m_median[col] = df_m[col].fillna(df_m[col].dropna().median())
    df_m_mode[col] = df_m[col].fillna(df_m[col].dropna().mode()[0])
    
print('Mean imputation nulls: ', df_m_mean.isnull().sum().sum())
print('Median imputation nulls: ', df_m_median.isnull().sum().sum())
print('Mode imputation nulls: ', df_m_mode.isnull().sum().sum())

imp_knn = KNNImputer(n_neighbors = 2)
df_m_knn = imp_knn.fit_transform(df_m_knn)
df_m_knn = pd.DataFrame(df_m_knn)
print('Knn imputation nulls: ', df_m_knn.isnull().sum().sum())

lr = LinearRegression()
rf = RandomForestRegressor()

def impute_missing_data(model):
    if model == lr:
        df = deepcopy(df_m_lr)
    elif model == rf:
        df = deepcopy(df_m_rf)
    # Loop through each column that has null values to impute for each row in that column with predictions from model
    for col in null_columns:
        df_cc = df.dropna() #use complete case
        
        # Fit model
        X = df_cc.drop(columns = col)
        y = df_cc[col]
        model.fit(X, y)
        
        df_temp = deepcopy(df) #deep copy to avoid making update
        
        # Fillna temporarily for other columns with median - eventually all columns will be imputed with model, but in the meantime impute columns left to be imputed with the median
        for column in df_temp.columns:
            if column != col:
                df_temp[column] = df_temp[column].fillna(df_temp[column].dropna().median())
                
        X_temp = df_temp.drop(columns = col) #drop target for prediction so there is no nulls

        # Loop through all of the rows checking for nulls in the col column, create a pred, and set that cell equal to pred
        for index, row in df_temp.iterrows():
            if pd.isnull(df_temp[col].iloc[index]):
                X_test_row = X_temp.iloc[index] #use df without target
                X_test_row = X_test_row.values.reshape(1, -1)
                
                pred = model.predict(X_test_row)
                df_temp.loc[index, col] = pred
                #print(pred[0])
        df[col] = df_temp[col] #make updates to df for next loop
    return df
        
df_m_lr = impute_missing_data(lr)
print('Lr imputation nulls: ', df_m_lr.isnull().sum().sum())

df_m_rf = impute_missing_data(rf)
print('Rf imputation nulls: ',df_m_rf.isnull().sum().sum())

Mean imputation nulls:  0
Median imputation nulls:  0
Mode imputation nulls:  0
Knn imputation nulls:  0
Lr imputation nulls:  0
Rf imputation nulls:  0

## Export to CSVs

In [23]:
df_m_mean.to_csv('./cleaned_dataframes/df_m_mean.csv', index = False)
df_m_median.to_csv('./cleaned_dataframes/df_m_median.csv', index = False)
df_m_mode.to_csv('./cleaned_dataframes/df_m_mode.csv', index = False)
df_m_knn.to_csv('./cleaned_dataframes/df_m_knn.csv', index = False)
df_m_lr.to_csv('./cleaned_dataframes/df_m_lr.csv', index = False)
df_m_rf.to_csv('./cleaned_dataframes/df_m_rf.csv', index = False)